# Generated by Django 2.2.13 on 2020-08-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_cleric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fellowships/photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleric', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fellowship', to='accounts.Cleric')),
                ('members', models.ManyToManyField(blank=True, related_name='fellowships', to='accounts.Member')),
            ],
            options={
                'verbose_name': 'fellowship',
                'verbose_name_plural': 'fellowships',
            },
        ),
    ]
