# Generated by Django 2.2.13 on 2020-08-08 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cleric',
                'verbose_name_plural': 'clerics',
            },
        ),
    ]
